services:
  postgres:
    image: postgres:16
    container_name: pg_delivery
    environment:
      POSTGRES_DB: delivery
      POSTGRES_USER: delivery
      POSTGRES_PASSWORD: delivery
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis_delivery
    ports:
      - '6379:6379'

  keycloak:
    image: quay.io/keycloak/keycloak:25.0.2
    container_name: keycloak_delivery
    command:
      - start-dev
      - --import-realm
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HEALTH_ENABLED: "true"
      KC_METRICS_ENABLED: "true"
      KC_HTTP_RELATIVE_PATH: "/"
    volumes:
      - ./keycloak/realm-delivery-export.json:/opt/keycloak/data/import/realm.json
      - keycloak_data:/opt/keycloak/data
    ports:
      - '8081:8080'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health/ready"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  pgdata:
  keycloak_data: